'use strict';

const { Version2Client } = require('jira.js');
const { preview } = require('./slack');

const TRANSITION_NAMES = {
  [process.env.ID_TO_DO]:       'To Do',
  [process.env.ID_IN_PROGRESS]: 'In Progress',
  [process.env.ID_IN_REVIEW]:   'In Review',
  [process.env.ID_QA_READY]:    'QA Ready',
  [process.env.ID_QA_FAILED]:   'QA Failed',
  [process.env.ID_IN_TEST]:     'In Test',
  [process.env.ID_QA_SUCCESS]:  'QA Success',
  [process.env.ID_WILL_NOT_FIX]:'Will Not Fix',
};

// Defines which status the ticket must currently be in before transitioning.
// Evaluated lazily so env vars are read at call time, not module load time.
function requiredCurrentStatus(transitionId) {
  if (transitionId === process.env.ID_IN_PROGRESS) return 'To Do';
  if (transitionId === process.env.ID_IN_REVIEW)   return 'In Progress';
  if (transitionId === process.env.ID_QA_READY)    return 'In Review';
  return null; // no restriction for other transitions
}

const client = new Version2Client({
  host: process.env.JIRA_HOST,
  authentication: {
    basic: {
      email: process.env.JIRA_EMAIL,
      apiToken: process.env.JIRA_TOKEN,
    },
  },
});

/**
 * Transitions a Jira issue to a new status.
 * Swallows errors silently — already-transitioned tickets return 400 and that's fine.
 *
 * @param {string} issueKey
 * @param {string} transitionId
 */
async function transitionIssue(issueKey, transitionId) {
  if (!transitionId) return false;

  const required = requiredCurrentStatus(transitionId);
  const issue = await client.issues.getIssue({ issueIdOrKey: issueKey });
  const currentStatus = issue.fields.status.name;

  if (required && currentStatus !== required) {
    console.log(`[Jira] Skipping ${issueKey}: status is "${currentStatus}", expected "${required}"`);
    return false;
  }

  // Block "To Do → In Progress" for tickets in the backlog sprint (id 249)
  if (transitionId === process.env.ID_IN_PROGRESS) {
    const sprints = issue.fields.customfield_10010 || [];
    const inBacklog = sprints.some(s => s.id === 249);
    if (inBacklog) {
      console.log(`[Jira] Skipping ${issueKey}: ticket is in Active Sprint Backlog (249)`);
      return false;
    }
  }

  const statusName = TRANSITION_NAMES[transitionId] || `id ${transitionId}`;

  // Scrum Master rule: an "In Progress" → "In Review" transition requires a worklog first.
  if (transitionId === process.env.ID_IN_REVIEW) {
    await createWorklog(issueKey);
  }

  await preview(`🔄 *Jira transition*\nTicket: \`${issueKey}\`\nAction: \`${currentStatus}\` → \`${statusName}\``);

  try {
    await client.issues.doTransition({
      issueIdOrKey: issueKey,
      transition: { id: transitionId },
    });
    console.log(`[Jira] Transitioned ${issueKey} → ${statusName}`);
    return true;
  } catch (err) {
    console.log(`[Jira] transitionIssue(${issueKey}, ${transitionId}) failed:`, err.message);
    return false;
  }
}

/**
 * Adds a worklog to a Jira issue.
 * Defaults: 1 hour, today 12:00 GMT+7, the canonical "implement + self-test" description.
 *
 * @param {string} issueKey
 * @param {{ timeSpentSeconds?: number, started?: string, description?: string }} [opts]
 */
async function createWorklog(issueKey, opts = {}) {
  const timeSpentSeconds = opts.timeSpentSeconds ?? 3600;
  const description = opts.description
    ?? 'Implement based on solution design & implementation plan, self-review, self-test';
  // Today's date in GMT+7 (yyyy-MM-dd) so worklog is logged on the local working day.
  const todayGmt7 = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' });
  const started = opts.started ?? `${todayGmt7}T12:00:00.000+0700`;

  const comment = `[Generated by personal bot] ${description}`;

  await preview(`⏱️ *Jira worklog*\nTicket: \`${issueKey}\`\nTime: \`${timeSpentSeconds}s\` Started: \`${started}\`\nComment: ${comment}`);

  try {
    await client.issueWorklogs.addWorklog({
      issueIdOrKey: issueKey,
      timeSpentSeconds,
      started,
      comment,
    });
    console.log(`[Jira] Worklog added to ${issueKey} (${timeSpentSeconds}s @ ${started})`);
  } catch (err) {
    console.log(`[Jira] createWorklog(${issueKey}) failed:`, err.message);
  }
}

/**
 * Adds a plain-text comment to a Jira issue using ADF format.
 *
 * @param {string} issueKey
 * @param {string} text
 */
async function addComment(issueKey, text) {
  await preview(`💬 *Jira comment*\nTicket: \`${issueKey}\`\nComment: ${text}`);

  try {
    await client.issueComments.addComment({
      issueIdOrKey: issueKey,
      comment: text,
    });
    console.log(`[Jira] Comment added to ${issueKey}`);
  } catch (err) {
    console.log(`[Jira] addComment(${issueKey}) failed:`, err.message);
  }
}

/**
 * Fetches a Jira issue with all fields.
 *
 * @param {string} issueKey
 * @returns {Promise<object>}
 */
async function getIssue(issueKey) {
  return client.issues.getIssue({ issueIdOrKey: issueKey });
}

/**
 * Fetches just the summary (title) of a Jira issue. Returns null if the issue
 * doesn't exist or the API errors — callers must handle null gracefully.
 *
 * @param {string} issueKey
 * @returns {Promise<string|null>}
 */
async function getIssueSummary(issueKey) {
  try {
    const issue = await client.issues.getIssue({ issueIdOrKey: issueKey, fields: ['summary'] });
    return issue.fields?.summary ?? null;
  } catch (err) {
    console.log(`[Jira] getIssueSummary(${issueKey}) failed:`, err.message);
    return null;
  }
}

module.exports = { transitionIssue, addComment, getIssue, createWorklog, getIssueSummary };
